//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms_lab_6_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer(int id, string Name, int age)
        {
            CUS_AC_Account_ID = id;
            CUS_FullName = Name;
            CUS_Age = age;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OrdersInProgresses = new HashSet<OrdersInProgress>();
            this.Portfolios = new HashSet<Portfolio>();
        }
    
        public int CUS_AC_Account_ID { get; set; }
        public string CUS_FullName { get; set; }
        public int CUS_Age { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersInProgress> OrdersInProgresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Portfolio> Portfolios { get; set; }
    }
}
